// Helpers for league event lineups.
//
// Conventions:
//  - A lineup belongs to a (event, team) pair where the event has a roundId
//    set (i.e. it's a league-attached event for a specific round).
//  - Each lineup is a list of slots, grouped by category and ordered by
//    slotNumber (1-based). Slot N from team A plays slot N from team B.
//  - Lineups are kept private until both teams submit; once both submit,
//    they are revealed and LeagueGame rows are auto-generated by the
//    matching algorithm in `generateGamesFromLineups`.

import { prisma } from "@/lib/db";

export interface LineupSlotInput {
  categoryId: string;
  slotNumber: number;
  player1Id: string;
  player2Id?: string | null;
}

export interface LeagueConfig {
  maxRoster?: number;
  maxPointsPerMatchDay?: number;
  minMatchDaysForPlayoff?: number;
  maxMatchesPerEvent?: number;
  allowCrossCategoryPlay?: boolean;
}

export interface CategoryRules {
  id: string;
  format: string;          // "doubles" | "singles"
  gender: string;          // "male" | "female" | "mix" | "open"
  ageGroup: string;        // "open" | "35+" | ...
  skillMin: number | null;
  skillMax: number | null;
  maxPerEvent: number | null;
  sortOrder: number;
}

export interface PlayerLite {
  id: string;
  gender: string | null;
  duprRating: number | null;
  // age can be derived later when we add date-of-birth; ignored for now.
}

/**
 * Validate a single slot's player picks against the category and roster.
 * Returns null if valid, or a string error message if not.
 *
 * If `enforceEligibility` is false, gender / age / skill checks are skipped
 * (used when an organizer / admin overrides). Roster + format checks are
 * always enforced.
 */
export function validateSlot(
  slot: LineupSlotInput,
  category: CategoryRules,
  rosterById: Map<string, PlayerLite>,
  enforceEligibility: boolean,
): string | null {
  const p1 = rosterById.get(slot.player1Id);
  if (!p1) return "Player 1 not on team roster";

  const isDoubles = category.format === "doubles";
  if (isDoubles && !slot.player2Id) return "Doubles slot requires two players";
  if (!isDoubles && slot.player2Id) return "Singles slot must have only one player";

  let p2: PlayerLite | undefined;
  if (slot.player2Id) {
    if (slot.player2Id === slot.player1Id) return "Doubles slot must have two different players";
    p2 = rosterById.get(slot.player2Id);
    if (!p2) return "Player 2 not on team roster";
  }

  if (!enforceEligibility) return null;

  // Gender rules:
  //   "male" → both players male
  //   "female" → both players female
  //   "mix" → one male + one female (doubles only)
  //   "open" → no gender restriction
  if (category.gender === "male") {
    if (p1.gender !== "M") return "Category requires male players";
    if (p2 && p2.gender !== "M") return "Category requires male players";
  } else if (category.gender === "female") {
    if (p1.gender !== "F") return "Category requires female players";
    if (p2 && p2.gender !== "F") return "Category requires female players";
  } else if (category.gender === "mix" && p2) {
    const genders = new Set([p1.gender, p2.gender]);
    if (!(genders.has("M") && genders.has("F"))) {
      return "Mixed doubles requires one male + one female";
    }
  }

  // Skill rules — only check if both bounds are set; missing DUPR rating
  // means the player is unrated and we can't check, so let it through.
  if (category.skillMin != null) {
    if (p1.duprRating != null && p1.duprRating < category.skillMin) return `Player below category min (${category.skillMin})`;
    if (p2?.duprRating != null && p2.duprRating < category.skillMin) return `Player below category min (${category.skillMin})`;
  }
  if (category.skillMax != null) {
    if (p1.duprRating != null && p1.duprRating > category.skillMax) return `Player above category max (${category.skillMax})`;
    if (p2?.duprRating != null && p2.duprRating > category.skillMax) return `Player above category max (${category.skillMax})`;
  }

  // ageGroup not enforced yet — schema doesn't store DOB.
  return null;
}

/** Validate a full lineup — all slots, plus same-category and cross-category rules. */
export function validateLineup(
  slots: LineupSlotInput[],
  categoriesById: Map<string, CategoryRules>,
  rosterById: Map<string, PlayerLite>,
  config: LeagueConfig,
  enforceEligibility: boolean,
): string | null {
  // Per-slot
  for (const s of slots) {
    const cat = categoriesById.get(s.categoryId);
    if (!cat) return `Unknown category: ${s.categoryId}`;
    const err = validateSlot(s, cat, rosterById, enforceEligibility);
    if (err) return err;
  }

  // Per-category caps + duplicate slot numbers + same-player-twice within category
  const byCat = new Map<string, LineupSlotInput[]>();
  for (const s of slots) {
    const arr = byCat.get(s.categoryId) || [];
    arr.push(s);
    byCat.set(s.categoryId, arr);
  }
  for (const [catId, arr] of byCat) {
    const cat = categoriesById.get(catId)!;
    if (cat.maxPerEvent != null && arr.length > cat.maxPerEvent) {
      return `Too many slots for ${catId}: max ${cat.maxPerEvent}`;
    }
    const slotNums = new Set<number>();
    const playerIds = new Set<string>();
    for (const s of arr) {
      if (slotNums.has(s.slotNumber)) return `Duplicate slot number ${s.slotNumber} in same category`;
      slotNums.add(s.slotNumber);
      if (playerIds.has(s.player1Id)) return `Same player used twice in same category`;
      playerIds.add(s.player1Id);
      if (s.player2Id) {
        if (playerIds.has(s.player2Id)) return `Same player used twice in same category`;
        playerIds.add(s.player2Id);
      }
    }
  }

  // Cross-category — only checked if league disallows it
  if (config.allowCrossCategoryPlay === false) {
    const seen = new Set<string>();
    for (const s of slots) {
      if (seen.has(s.player1Id)) return `Cross-category play disallowed; player used in multiple categories`;
      seen.add(s.player1Id);
      if (s.player2Id) {
        if (seen.has(s.player2Id)) return `Cross-category play disallowed; player used in multiple categories`;
        seen.add(s.player2Id);
      }
    }
  }

  return null;
}

/**
 * Pair team A's slots vs team B's slots and produce LeagueGame rows.
 * Caller is responsible for opening / committing the transaction.
 *
 * Algorithm:
 *   For each category (sorted by sortOrder):
 *     pairs[i] = (A.slot[i], B.slot[i]) for i in 0..min(|A|, |B|, maxPerEvent)
 *   All pairs start as isPrincipal=true.
 *   If overall total > maxMatchesPerEvent, demote highest-slotNumber overflow
 *   to isPrincipal=false (slot 1 is most important).
 */
export function planGames(
  aSlots: { categoryId: string; slotNumber: number; player1Id: string; player2Id: string | null }[],
  bSlots: { categoryId: string; slotNumber: number; player1Id: string; player2Id: string | null }[],
  categories: CategoryRules[],
  config: LeagueConfig,
): {
  categoryId: string;
  slotNumber: number;
  aPlayers: string[];
  bPlayers: string[];
  isPrincipal: boolean;
}[] {
  const cats = [...categories].sort((a, b) => a.sortOrder - b.sortOrder);
  const pairs: {
    categoryId: string;
    slotNumber: number;
    categorySortOrder: number;
    aPlayers: string[];
    bPlayers: string[];
  }[] = [];

  for (const cat of cats) {
    const aBy = new Map<number, typeof aSlots[number]>();
    const bBy = new Map<number, typeof bSlots[number]>();
    for (const s of aSlots) if (s.categoryId === cat.id) aBy.set(s.slotNumber, s);
    for (const s of bSlots) if (s.categoryId === cat.id) bBy.set(s.slotNumber, s);
    const slotNums = [...new Set([...aBy.keys(), ...bBy.keys()])].sort((a, b) => a - b);
    let made = 0;
    for (const n of slotNums) {
      const a = aBy.get(n);
      const b = bBy.get(n);
      if (!a || !b) continue;
      if (cat.maxPerEvent != null && made >= cat.maxPerEvent) break;
      const aP = [a.player1Id, ...(a.player2Id ? [a.player2Id] : [])];
      const bP = [b.player1Id, ...(b.player2Id ? [b.player2Id] : [])];
      pairs.push({ categoryId: cat.id, slotNumber: n, categorySortOrder: cat.sortOrder, aPlayers: aP, bPlayers: bP });
      made++;
    }
  }

  // Default: all principal
  const out = pairs.map((p) => ({ ...p, isPrincipal: true }));

  // Overall cap: demote excess starting from highest slotNumber, then highest categorySortOrder
  const max = config.maxMatchesPerEvent;
  if (max != null && out.length > max) {
    const sorted = [...out]
      .map((p, idx) => ({ ...p, idx }))
      .sort((a, b) =>
        b.slotNumber - a.slotNumber ||
        b.categorySortOrder - a.categorySortOrder
      );
    const demote = sorted.slice(0, out.length - max);
    for (const d of demote) out[d.idx].isPrincipal = false;
  }

  return out.map(({ categorySortOrder: _csOrder, ...rest }) => { void _csOrder; return rest; });
}

/**
 * Reveal both lineups and create LeagueGame rows in the database.
 * Idempotent-ish: deletes any prior lineup-generated games (without a
 * winner) for this event before creating new ones.
 */
export async function revealAndGenerate(eventId: string) {
  const event = await prisma.event.findUnique({
    where: { id: eventId },
    include: {
      leagueLineups: { include: { slots: true } },
      round: { include: { league: { include: { categories: true } } } },
    },
  });
  if (!event) throw new Error("Event not found");
  if (!event.round) throw new Error("Event is not attached to a league round");
  const lineups = event.leagueLineups;
  if (lineups.length !== 2) throw new Error("Need exactly two lineups");
  const [a, b] = lineups;
  const cats: CategoryRules[] = event.round.league.categories.map((c) => ({
    id: c.id,
    format: c.format,
    gender: c.gender,
    ageGroup: c.ageGroup,
    skillMin: c.skillMin,
    skillMax: c.skillMax,
    maxPerEvent: c.maxPerEvent,
    sortOrder: c.sortOrder,
  }));
  const config = (event.round.league.config as LeagueConfig | null) || {};
  const aSlots = a.slots.map((s) => ({ categoryId: s.categoryId, slotNumber: s.slotNumber, player1Id: s.player1Id, player2Id: s.player2Id }));
  const bSlots = b.slots.map((s) => ({ categoryId: s.categoryId, slotNumber: s.slotNumber, player1Id: s.player1Id, player2Id: s.player2Id }));
  const planned = planGames(aSlots, bSlots, cats, config);

  await prisma.$transaction(async (tx) => {
    // Clean up any prior auto-generated games without a recorded winner
    await tx.leagueGame.deleteMany({
      where: { eventId, lineupGenerated: true, winnerId: null },
    });
    for (const g of planned) {
      const game = await tx.leagueGame.create({
        data: {
          eventId,
          categoryId: g.categoryId,
          team1Id: a.teamId,
          team2Id: b.teamId,
          isPrincipal: g.isPrincipal,
          lineupGenerated: true,
        },
      });
      const allPlayerIds = [...g.aPlayers, ...g.bPlayers];
      for (const pid of allPlayerIds) {
        await tx.leagueGamePlayer.create({ data: { leagueGameId: game.id, playerId: pid } });
      }
    }
    await tx.leagueLineup.updateMany({ where: { eventId }, data: { status: "revealed" } });
  });
}
